### ISSUE TITLE
Cannot access the dataset mentioned

### ISSUE THREAD

**Issue by kamalchaturvedi** [aaravindravi/A-Dataset-and-Preliminary-Results-for-Umpire-Pose-Detection-Using-SVM-Classification-of-Deep-Feature#1]
Hello Aravind,

I am looking forward to do a similar project on highlights generation from cricket videos, but I hvnt been able to access any well labeled video dataset which I can use for this project. Also, I could not access the google drive link posted in this repo's readme page.

It would be of great help if you could guide me to a relevant dataset.
Best Regards,
Kamal

**Comment by aaravindravi** [comment]
Hello Kamal,

Thank you for writing to us regarding the issue with the link. We found that the link was not accessible, after getting some help we have been able to fix the issue with the link. Please check the same link for downloading the dataset and if you still face issues let us know. For the cricket videos, we synthesized 2 videos with a set number of events for performance evaluation. If you are looking for other videos to test on then I would suggest looking up some on YouTube and downloading them.
Hope you find this helpful.

Thanks and Regards,
Aravind Ravi

**Comment by kamalchaturvedi** [comment]
Great Aravind. I have sent a request to allow access to the dataset. Kindly approve it :)

Yes, Youtube is the only place I could find full cricket matches. I duly appreciate your help on this.

Best Regards,
Kamal
