### ISSUE TITLE
IndexError: index 2048 is out of bounds for axis 1 with size 2....how to resolve this error?

### ISSUE THREAD

**Issue by shaheer2019** [aaravindravi/A-Dataset-and-Preliminary-Results-for-Umpire-Pose-Detection-Using-SVM-Classification-of-Deep-Feature#2]
The following error **"IndexError: index 2048 is out of bounds for axis 1 with size 2".** 
I am quite new to machine learning so I do not have any idea about how to solve this. Any kind of help would be appreciated.

**#Storing the extracted features**
X=[]
X1 = np.load('class_1data_model1.npy')
X2 = np.load('class_2data_model1.npy')
X_data = np.append(X1,X2,axis=0)
Y_data = X_data[:,2048]
X_data = X_data[:,1:2048]
x_tr,x_ts,y_tr,y_ts = train_test_split(X_data, Y_data, test_size=0.2,random_state=10)

**Comment by aaravindravi** [comment]
Hello shaheer,
Have you generated the class_1data_model1.npy and class_2data_model1.npy?
The code provided was an example of the implementation. 

The idea is to get the features of an input image by forward propagating the image through a pre-trained network and extracting the bottleneck features. In this case, if you are using the inceptionv3 - 1024 is the size of the feature vector, if you are using VGG19 then it would be 2048.

So I would suggest you have a look at the feature extraction scripts. This script is responsible for the feature extraction step, in the end, the features for all the images will be stored in a file. Then you would have to load these features in the classifier script to build the SVM classifier using these features.

Let me know if this helps. I would be glad to provide any further clarification.

**Comment by aaravindravi** [comment]
Issue closed as it is same as https://github.com/aaravindravi/A-Dataset-and-Preliminary-Results-for-Umpire-Pose-Detection-Using-SVM-Classification-of-Deep-Feature/issues/3
Please continue in the other thread.
