### ISSUE TITLE
Error occur when split data

### ISSUE THREAD

**Issue by saba-dep** [aaravindravi/A-Dataset-and-Preliminary-Results-for-Umpire-Pose-Detection-Using-SVM-Classification-of-Deep-Feature#4]
hi, i try to run your code but , I have an issue when execute the classifier1 and also classifier 2 in this line of code:

#Labels
Y_data = X_data[:,(X_data.shape[1]-1)]
#Training Data
X_data = X_data[:,0:(X_data.shape[1]-1)]
x_tr,x_ts,y_tr,y_ts = train_test_split(X_data, Y_data, test_size=0.3,random_state=10)
......
..
and hare is error

**'(0,1) range'.format(test_size, n_samples))

ValueError: test_size=0 should be either positive and smaller than the number of samples 0 or a 
 float in the (0,1) range**
kindly help me.
thanks in advance

**Comment by aaravindravi** [comment]
Hi Saba, I have refactored the code and restructured the repo. Also, I have added the respective output files for your validation. This has been tested. Please update your local repo. Hope this helps fix some of the issues you might be facing.
